# This is the config file used to generate the README for the project.

# There is no Go code examples in the docs, so use defaults.
fencedCodeLanguage = ""

customMarkdownBadges = [
  "[![Build Status](https://travis-ci.com/dmjones/goreadme.svg?branch=master)](https://travis-ci.com/dmjones/goreadme)"
]